# Generated by Django 4.1.1 on 2022-09-16 07:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(db_index=True, default=datetime.datetime(2022, 9, 16, 7, 25, 11, 601541, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default=datetime.datetime(2022, 9, 16, 7, 25, 42, 888300, tzinfo=datetime.timezone.utc), max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
