# Generated by Django 4.1.1 on 2022-09-22 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=20)),
                ('food', models.CharField(max_length=20)),
                ('hobby', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
